services:
  db:
    image: postgres:16-alpine
    container_name: postgres_flx
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=flx
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
