services:
  db_2025_4T:
    image: postgres:16-alpine
    container_name: cadoc_2025_4T
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cdc
    ports:
      - "5435:5432"
    volumes:
      - ./db_2025_4T:/var/lib/postgresql/data
  db_2025_3T:
    image: postgres:16-alpine
    container_name: cadoc_2025_3T
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cadoc
    ports:
      - "5432:5432"
    volumes:
      - ./db_2025_3T:/var/lib/postgresql/data
