services:
  db:
    image: postgres:16-alpine
    container_name: postgres_reg
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=reg
    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
